---
title: "R Project 1 - Hello R"
author: "Cristy  Limones"
date: "Due Sep 8"
output: 
  html_document: 
    fig_width: 9
    fig_height: 9
    highlight: pygments
    theme: cosmo
---

MAKE SURE YOU READ AND FOLLOW **ALL** INSTRUCTIONS ON THE INSTRUCTION DOCUMENT. 

<!-- ### Load packages -->

```{r load-packages, message=FALSE, echo = FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

- datasaurus_dozen has 1846 rows and 12 datasets
- data set, x-values, and y-values

<!-- (Type your answer to Exercise 1 here. This exercise does not require any R code. **Remove notes like this in the final product that you turn in**) -->

### Exercise 2



<!-- (The answers for this Exercise are given for you below. But you should clean up some of the narrative so that it only includes what you want to turn in.) -->

<!-- First let's plot the data in the dino dataset: -->

 ```{r plot-dino, fig.height=3, fig.width=6, echo=FALSE} 
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

<!-- And next calculate the correlation between `x` and `y` in this dataset: -->

```{r cor-dino, echo=FALSE}
dino_data %>%
  summarize(r = cor(x, y))
```


### Exercise 3

<!-- (Add code and narrative as needed. Note that the R chunks are labeled with `plot-star` and `cor-star` to provide spaces to place the code for plotting and calculating the correlation coefficient. To finish, remember to clean up the narrative by removing these instructions.) -->



```{r plot-star, fig.height=3, fig.width=3, echo=FALSE}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +  geom_point() 
```

<!-- I'm some text, you should replace me with more meaningful text... -->
 
```{r cor-star, echo=FALSE}
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4

(Add code and narrative as needed. Note that two R chunks are given but they are not labeled. Use the convention from above to name them appropriately.)


```{r plot-circle, fig.height=3, fig.width=3, echo=FALSE}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) + geom_point()
```

```{r cor-cir le, echo = FALSE}
circle_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5


```{r, echo = FALSE}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) +   geom_point() + facet_wrap(~ dataset, ncol = 3) + # facet      the dataset variable in cols
  theme(legend.position = "none")
```

```{r, echo =FALSE}
datasaurus_dozen %>% 
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```

<!-- (Add code and narrative as needed. To add R chunks either type out the backticks, curly braces, and the letter `r` or use the Insert chunk button above, with the green +C.) -->
